---
apiVersion: v1
kind: Pod
metadata:
    name: gameoflife
spec:
    containers:
        - image: qualitythought/gameoflife:07112020
          name: gameoflife
          ports:
            - containerPort: 8080
              name: golhttp
              protocol: TCP
    

