---
apiVersion: v1
kind: Pod
metadata:
    name: gameoflife
spec:
    containers:
        - image: qualitythought/gameoflife:07112020
          name: gameoflife
          ports:
            - containerport: 8080
              name: gol http
              protocol: Tcp
    

